### ISSUE TITLE
Provide additional information about how to use it

### ISSUE THREAD

**Issue by kdober** [Gimly/vscode-qlik#9]
Hi, This seems a great tool, and I'm trying to understand how it works.
I have read the documentation, and it is not clear for me how to make use of it (for example, with our Qlik sense enterprise server).
Do we need to install anything on the QS server? If so, what and how?
How shall we fill the connection settings on my local VScode to connect to the server? Could you provide an example how to fill it?

Thanks a lot
Best regards!

**Comment by Midnex** [comment]
@pepitolanda currently I do not know if there is a way to connect to your Qlik server. This is merely syntax highlighting support. 

How I work with it now is I have a network drive mapped to the folder where I store my qlik code, then I edit the code within vscode.

For example my network drive is \\qlik-ent\db\blah\blah
I open this folder within vscode

In my qlik applications I have the following line for each file I load (I like to keep things separated as much as possible, when possible.)

$(Must_Include='lib://qlik-ent/db/blah/blah/main.qvs');
$(Must_Include='lib://qlik-ent/db/blah/blah/sometable.qvs');
$(Must_Include='lib://qlik-ent/db/blah/blah/someothertables.qvs');

I can actively change things in vscode (despite some issues with syntax highlighting) saving it, then loading it in qlik via Load Data.

This is also super helpful if you accidentally push something to publish, and don't make a backup copy for updates to be done in. Cause if you do, you can replicate it easier with all the load scripts on the network instead of the app.

**Comment by kdober** [comment]
Hi, thanks for your answer.
We are the same thing for the scripts :)
What called my attention from this extension is that you can connect directly to QS server and work over the apps.
After a few attempts I was able to set up the connection to the server, and it magically retrieves all the apps in it, and you can explore and modify dimensions, measures, script, visualizations, etc. It's very nice.
I just filled in the server url, form authentication and added my doman\user and password, and it worked (windows authentication)

**Comment by Gimly** [comment]
@pepitolanda I think you've got the wrong extension 😄. This one is a bit outdated as I'm not working with Qlik anymore. The one I think you're talking about which has sync with QS server is called vscode4qlik.

Their GitHub is over here: https://github.com/q-masters/vsqlik

Maybe I should remove this one from the marketplace, as the other looks way more feature complete.

**Comment by kdober** [comment]
Hi @Gimly 

You are right. I'm sorry for the confusion :) 
Thanks!

**Comment by Gimly** [comment]
No worries
